name: tests
on:
  push:
  pull_request:
    types:
      - 'opened'
      - 'closed'
      - 'reopened'
      - 'synchronize'
  #  paths:
  #  - '*.md'
  #  - '*.xml'
  #  - '*.html'
  #  - '*.properties'
  #  - '*.kt*'
  #  branches: [ master, main ]
env:
  JAVA_VERSION: 17
  NODE_VERSION: 17.7.2
jobs:
  tests:
    if: github.event.inputs.trigger == ''
      || !startsWith(github.event.inputs.trigger, 'm')
      || !startsWith(github.event.inputs.trigger, 'M')
    name: check java-${{ matrix.java }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.npm
            ~/.docker
            ~/.gradle
          key: ${{ runner.os }}-build-${{ hashFiles('**/*gradle*', '**/pom.xml') }}
      - run: cd $GITHUB_WORKSPACE ; ./gradlew --no-daemon --stop
      - run: cd $GITHUB_WORKSPACE ; ./gradlew --no-daemon --console=plain -S clean build
      - run: cd $GITHUB_WORKSPACE ; ./mvnw clean verify
